//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hash_table.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>1001,1,Jersey_Cow</string>
  <string>1002,1,Jersey_Cow</string>
  <string>1003,1,Jersey_Cow</string>
  <string>1004,1,Cow</string>
  <string>1005,1,Cow</string>
  <string>1006,1,Cow</string>
  <string>1007,1,Goat</string>
  <string>1008,1,Goat</string>
  <string>1009,1,Goat</string>
  <string>1010,1,Goat</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection dataSource
        {
            get
            {
                return ((global::System.Collections.Specialized.StringCollection)(this["dataSource"]));
            }
        }
    }
}
